CFLAGS = -DTEST

OBJS = clock.o console.o sdram.o lcd-spi.o gfx.o 

BINARY = seismograph

LDLIBS += -lm

LDSCRIPT = ../stm32f429i-discovery.ld

OOCD_INTERFACE = stlink-v2-1

include ../../Makefile.include
